// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS5X8-W2TZoAVuDYD8ACgqbqm-0v_51oE',
    appId: '1:603714734257:web:2067c674ec1841b7a0fa90',
    messagingSenderId: '603714734257',
    projectId: 'todo-with-unit-test',
    authDomain: 'todo-with-unit-test.firebaseapp.com',
    storageBucket: 'todo-with-unit-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZZMwNk1DmgknDdovtra4TyrpsPlhWxoc',
    appId: '1:603714734257:android:a82d27cca0812a46a0fa90',
    messagingSenderId: '603714734257',
    projectId: 'todo-with-unit-test',
    storageBucket: 'todo-with-unit-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj2KjfQAAcCZeeYqHL7hGii4b15i3FXPU',
    appId: '1:603714734257:ios:7d80e11b7f65af15a0fa90',
    messagingSenderId: '603714734257',
    projectId: 'todo-with-unit-test',
    storageBucket: 'todo-with-unit-test.appspot.com',
    iosClientId: '603714734257-d6sftkck7grkrn4m0kdbkmojf3ea054q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj2KjfQAAcCZeeYqHL7hGii4b15i3FXPU',
    appId: '1:603714734257:ios:7d80e11b7f65af15a0fa90',
    messagingSenderId: '603714734257',
    projectId: 'todo-with-unit-test',
    storageBucket: 'todo-with-unit-test.appspot.com',
    iosClientId: '603714734257-d6sftkck7grkrn4m0kdbkmojf3ea054q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTodoApp',
  );
}
